# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      ignore:
        - publish-dockerhub
    docker:
      - image: circleci/node:6.14.2
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test_coverage
      - store_artifacts:
          path: coverage/

  publish-docker-image:
    docker:
      - image: docker:18.05.0-ce-git
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build -t feature-express .
      - run:
          name: Tag image
          command: |
            PACKAGE_VERSION=$(cat package.json \
              | grep version \
              | head -1 \
              | awk -F: '{ print $2 }' \
              | sed 's/[",\t ]//g')
            docker tag feature-express $DOCKER_USER_ID/feature-express:latest
            docker tag feature-express $DOCKER_USER_ID/feature-express:$PACKAGE_VERSION
      - run:
          name: Login in Dockerhub
          command: |
            docker login -u $DOCKER_USER_ID -p $DOCKER_PASS
      - run:
          name: Push to Dockerhub
          command: |
            docker push $DOCKER_USER_ID/feature-express

workflows:
  version: 2
  publish-docker-image:
    jobs:
      - publish-docker-image:
          filters:
            branches:
              only:
                - publish-dockerhub
